PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mobile_number TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS movies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS theatres (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS movie_theatres (
  movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE RESTRICT,
  theatre_id INTEGER NOT NULL REFERENCES theatres(id) ON DELETE RESTRICT,
  PRIMARY KEY (movie_id, theatre_id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE RESTRICT,
  theatre_id INTEGER NOT NULL REFERENCES theatres(id) ON DELETE RESTRICT,
  seats TEXT NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('CARD', 'UPI')),
  total_price INTEGER NOT NULL CHECK (total_price = 450),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_movie_theatres_movie ON movie_theatres(movie_id, theatre_id);
CREATE INDEX IF NOT EXISTS idx_bookings_user_created ON bookings(user_id, created_at DESC);
